name: 'id-analyzer-action'
description: 'Analyze the quality of your identifiers for sure'
author: 'Remo Gresta'
inputs:
  repo:
    required: true
    description: 'name of the repository'
  owner:
    required: true
    description: 'owner of the repository'
  branch:
    required: false
    description: 'branch of the repository'
    default: 'master'
outputs:
  out:
    description: 'Test'
runs:
  using: node20
  main: dist/index.js
